---

- name: Get kernel version
  shell: uname -r
  register: kernel_version

- name: Install kernel-devel
  yum:
    name: "kernel-devel-{{ kernel_version.stdout }}"
    state: present

- name: Copy install script
  copy:
   dest: /opt/
   src: gpu_support
   owner: root
   group: root
   mode: 0755