#!/bin/bash
export DOCKER_IMAGE_VERSION=${ARGO_DOCKER_IMAGE_VERSION}
export HTTP_AUTH_USER_NAME=${ARGO_HTTP_AUTH_USER_NAME}
export ELASTIC_HOST=${ELASTIC_HOST}
export ELASTIC_PORT=${ELASTIC_PORT}
export ELASTIC_SSL=${ELASTIC_SSL}
export ELASTIC_CONFIG_SETTING_INDEX=${ARGO_ELASTIC_CONFIG_SETTING_INDEX}
export SRV_INSTANCES=${ARGO_SRV_INSTANCES}
export SRV_CPUS=${ARGO_SRV_CPUS}
export SRV_MEM=${ARGO_SRV_MEM}
