#!/bin/bash
export DOCKER_IMAGE_VERSION=${SQL_SERVER_DOCKER_IMAGE_VERSION}
export SRV_INSTANCES=${SQL_SERVER_SRV_INSTANCES}
export SRV_CPUS=${SQL_SERVER_SRV_CPUS}
export SRV_MEM=${SQL_SERVER_SRV_MEM}
export UM_SERVICE_URL=${UM_SERVICE_BACKEND_URL}/api/um-service/v0.1
export BAILE_URL="http://${BAILE_HOST}:9001"
export BAILE_USERNAME=${BAILE_USERNAME}
export HTTP_SERVER_PREFIX=${SQL_SERVER_API_PATH}
export DB_PROTOCOL="redshift"
export DB_HOST=${REDSHIFT_HOST}
export DB_PORT=${REDSHIFT_PORT}
export DB_NAME=${REDSHIFT_DATABASE}
export DB_USERNAME=${REDSHIFT_USER}
