version: '3.8'
# volume defined

volumes:
  esdata1:
    driver: local
  esdata2:
    driver: local
  esdata3:
    driver: local
  mongo:
    driver: local

# network defined.

networks:
  studio9:

#Now all the services have beeen defined as per the Studio9 dependency.

services:
  
  # Elastic search :- 

  es-master-1:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.4
    container_name: es-master-1
    env_file:
      - ./envs/es-master-1.env
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - 20000:9200
    networks:
      - studio9
  
  es-data-1:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.4
    env_file:
      - ./envs/es-data-1.env
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
    depends_on:
    - es-master-1
    volumes:
      - esdata2:/usr/share/elasticsearch/data
    networks:
      - studio9
  
  es-data-2:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.4
    env_file:
      - ./envs/es-data-2.env
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
    volumes:
      - esdata3:/usr/share/elasticsearch/data
    networks:
      - studio9
    depends_on:
    - es-data-1
    - es-master-1
  
  es-migrate:
    image: ubuntu
    env_file:
      - ./envs/es-migrate.env
    volumes:
    - "$PWD/schema-migration/es-migrate:/es-migrate"
    networks:
      studio9:
    command:
    - "bash"
    - "-c"
    - |
      cd /es-migrate/scripts
      bash -x elasticsearch_init.sh

  # Service for Kibana is defined.
  
  kibana:
    image: kibana:5.6.4
    container_name: kibana
    ports:
      - 20001:5601
    env_file:
      - ./envs/kibana.env
    networks:
      studio9:
    depends_on:
    - es-data-1
    - es-master-1
    - es-data-2

  # Service for mongo is defined.
  
  mongo:
    image: mongo
    container_name: mongodb
    ports:
      - 20002:27017
    env_file:
      - ./envs/mongo.env
    networks:
      studio9:
    volumes:
      - mongo:/data/db
  
  mongo-migrate-um-svc:
    image: node
    volumes:
    - "$PWD/schema-migration/mongo-migrate/um-service:/um-service"
    container_name: migrate-um-mongo
    env_file:
      - ./envs/mongo-migrate.env
    command:
    - "bash"
    - "-c"
    - |
      cd /um-service
      bash -x migrateStagingMongo.sh
    networks:
      - studio9
    depends_on:
    - mongo

  mongo-migrate-baile:
    image: knoldusstudio9/baile:1.0
    container_name: migrate-baile-mongo
    env_file:
      - ./envs/mongo-migrate-baile.env
    entrypoint:
    - bin/mongo-migration-app
    networks:
      studio9:
    depends_on:
      - mongo
  
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    env_file:
      - ./envs/mongo-express.env
    networks:
      - studio9
    depends_on:
      - mongo
    ports:
    - 20003:8081
    command:
    - "sh"
    - "-c"
    - |
      sleep 30
      tini -- /docker-entrypoint.sh mongo-express

  # service for zookeper is defined.

  zookeeper:
    image: zookeeper
    hostname: zookeeper
    container_name: zookeeper
    ports:
    - 20004:2181
    restart: always
    networks:
      - studio9
  
  #Service for rabbit mq is defined.

  rabbit:
    image: rabbitmq:3-management
    container_name: rabbit
    hostname: rabbit
    ports:
    - 20005:5672
    - 20006:15672
    env_file:
      - ./envs/rabbit.env
    networks:
      - studio9

  # Aries service is defined.

  aries-rest-api:
    image: knoldusstudio9/aries-rest-api:1.0
    container_name: aries-rest
    depends_on:
    - es-data-1
    - es-master-1
    - es-data-2
    env_file:
      - ./envs/aries.env
    ports:
    - 20007:9000
    networks:
    - studio9
    healthcheck:
      test: ["CMD", "curl","-I","localhost:9000/v1/health"]
      interval: 4s
      timeout: 20s
      retries: 5
      start_period: 15s
    labels:
      maintainer: "MAyank"
      about: "Orion service"
    restart: unless-stopped

# Cortex service

  cortex-rest-api:
    image: knoldusstudio9/cortex-rest-api:1.0
    env_file:
     - ./envs/cortex.env
    ports:
    - 20008:9000
    networks:
    - studio9
    healthcheck:
      test: ["CMD", "curl","-I","localhost:9000/v1/health"]
      interval: 4s
      timeout: 20s
      retries: 5
      start_period: 15s
    depends_on:
    - aries-rest-api
    - rabbit

# argo-api-rest
  
  argo-api-rest:
    image: knoldusstudio9/argo-api-rest:1.0
    env_file:
     - ./envs/argo.env
    ports:
    - 20009:9000
    networks:
    - studio9
    healthcheck:
      test: ["CMD", "curl","-I","localhost:9000/v1/health"]
      interval: 4s
      timeout: 20s
      retries: 5
      start_period: 15s
    depends_on:
    - es-data-1
    - es-master-1
    - es-data-2

#   gemini service

  gemini:
    image: knoldusstudio9/gemini:1.0
    env_file:
     - ./envs/gemini.env
    ports:
    - 20010:7777
    networks:
    - studio9
    healthcheck:
      test: ["CMD", "curl","-I","localhost:7777/v1/health"]
      interval: 4s
      timeout: 20s
      retries: 5
      start_period: 15s
    depends_on:
    - zookeeper
    - sql-server

    #taurus service
  

  taurus:
    image: knoldusstudio9/taurus:1.0
    env_file:
     - ./envs/taurus.env
    ports:
    - 20011:9000
    networks:
    - studio9
    healthcheck:
      test: ["CMD", "curl","-I","localhost:9000/v1/health"]
      interval: 4s
      timeout: 20s
      retries: 5
      start_period: 15s
    depends_on:
    - rabbit
    - cortex-rest-api
    - baile
    - argo-api-rest
    - aries-rest-api

  #Orion service is defined.

  orion-rest-api:
    image: knoldusstudio9/orion-rest-api:2.0
    container_name: orion-rest
    depends_on: 
      - cortex-rest-api
      - zookeeper
      - rabbit
      
    env_file:
      - ./envs/orion.env
    ports:
      - 20012:9000
      - 20013:2552
    init: true
    networks:
      - studio9
    healthcheck:
      test: ["CMD", "curl","-I","localhost:9000/v1/health"]
      interval: 4s
      timeout: 20s
      retries: 5
      start_period: 15s
    
    
    labels:
      maintainer: "MAyank"
      about: "Orion service"
    restart: unless-stopped
    
    
# Pegasus service is defined.

  pegasus-rest-api:
    image: knoldusstudio9/pegasus-rest-api:1.0
    container_name: pegasus-rest
    depends_on:
      - taurus
      - postgres-db
      - rabbit
    env_file:
      - ./envs/pegasus.env
    ports:
      - 20014:9000
    init: true
    networks:
      - studio9
    healthcheck:
      test: ["CMD", "curl","-I","localhost:9000/v1/health"]
      interval: 4s
      timeout: 20s
      retries: 5
      start_period: 15s
    labels:
      maintainer: "MAyank"
      about: "Pegasus-service"
    restart: unless-stopped

  # um-Service
  um-service:
    image: knoldusstudio9/um-service:1.02
    container_name: um_service
    ports: 
      - "20015:9000"
    env_file:
      - ./envs/um_service.env
    networks:
      - studio9
    depends_on:
    - mongo

# baile
  baile:
    image: knoldusstudio9/baile:1.0
    container_name: baile
    ports: 
      - "20016:9000"
    env_file:
      - ./envs/baile.env
    networks:
      - studio9
    depends_on:
    - mongo
    - um-service
    - aries-rest-api
    - cortex-rest-api
    - sql-server
    - zookeeper





# sql-server

  sql-server:
    image: knoldusstudio9/sql-server:1.0
    container_name: sql-server
    ports: 
      - "20017:8000"
      - "20018:2552"
    env_file:
      - ./envs/sql.env
    networks:
      - studio9
    healthcheck:
      test: ["CMD", "curl","-I","localhost:8000/sql-server/v0.1/health"]
      interval: 4s
      timeout: 20s
      retries: 5
      start_period: 15s
    depends_on:
    - um-service

 # Salsa service - > The service for UI .
  salsa:
    image: knoldusstudio9/salsa-local:1.2
    container_name: salsa
    ports: 
      - "20019:80"
    env_file:
      - ./envs/salsa.env
    networks:
      - studio9
    depends_on:
    - baile

  # postgres
  postgres-db:
    image: postgres
    container_name: postgres-db
    restart: always
    env_file:
      - ./envs/postgres.env
    networks:
      - studio9 
    labels:
      maintainer: "MAyank"
      about: "Postgres-db"

  postgres-adminer:
    image: adminer
    depends_on:
      - postgres-db
    restart: always
    ports:
      - 20020:8080
    networks:
      - studio9
    healthcheck:
      test: ["CMD", "curl","-I","localhost:8080/v1/health"]
      interval: 4s
      timeout: 20s
      retries: 5
      start_period: 15s 
    labels:
      maintainer: "MAyank"
      about: "Postgres-adminer"   
