{{- if .Values.tls.enabled -}}
{{- $cn := printf "%s.%s.svc.cluster.local" ( include "mongodb.fullname" . ) .Release.Namespace }}
{{- $ca := genCA "myMongo-ca" 3650 -}}
{{- $cert := genSignedCert $cn nil nil 3650 $ca -}}
{{- $pem := printf "%s%s" $cert.Cert $cert.Key -}}
apiVersion: v1
kind: Secret
metadata:
  name: ca-clients
  namespace: {{ template "mongodb.namespace" . }}
  annotations:
    "helm.sh/hook": "pre-install"
  labels:
   {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: mongodb
type: Opaque
data:
  mongodb-ca-cert: {{ b64enc $ca.Cert }}
  mongodb-ca-key: {{ b64enc $ca.Key }}
  client-pem: {{ b64enc $pem }}
{{- end -}}
