---

  - name: disable selinux
    selinux: policy=targeted state=permissive

  - name: create group 'nogroup'
    group: name=nogroup state=present

  - name: disable IPv6 for all interfaces
    sysctl: name="net.ipv6.conf.all.disable_ipv6" value=1 sysctl_set=yes

  - name: disable IPv6 for default interface
    sysctl: name="net.ipv6.conf.default.disable_ipv6" value=1 sysctl_set=yes

  - name: enable ntpd
    service:
      name: ntpd
      enabled: yes
      state: started

  - name: disable firewalld
    service:
      name: firewalld
      enabled: no
      state: stopped
    register: firewalld_service_result
    failed_when: "'FAILED' in firewalld_service_result and 'Could not find the requested service' not in firewalld_service_result.msg"

