---

- name: Remove .ssh/authorized_keys
  file:
    state: absent
    path: "/home/{{main_user}}/.ssh/authorized_keys"

- name: Remove cloud-init logs
  file:
    state: absent
    path: "/var/log/cloud-init.log"



