#!/bin/bash
export DOCKER_IMAGE_VERSION=${RMQ_DOCKER_IMAGE_VERSION}
export USER=${RABBIT_USERNAME}
export SRV_INSTANCES=${RMQ_SRV_INSTANCES}
export SRV_CPUS=${RMQ_SRV_CPUS}
export SRV_MEM=${RMQ_SRV_MEM}
