{{ if .Values.msgTopologyOperator.metrics.enabled }}
apiVersion: v1
kind: Service
metadata:
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: messaging-topology-operator
    app.kubernetes.io/part-of: rabbitmq
    type: metrics
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  name: {{ template "rmqco.msgTopologyOperator.fullname" . }}-metrics
  namespace: {{ .Release.Namespace | quote }}
  {{- if or .Values.commonAnnotations .Values.msgTopologyOperator.metrics.service.annotations }}
  annotations:
    {{- if .Values.msgTopologyOperator.metrics.service.annotations }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.msgTopologyOperator.metrics.service.annotations "context" $ ) | nindent 4 }}
    {{- end }}
    {{- if .Values.commonAnnotations }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
    {{- end }}
  {{- end }}
spec:
  type: {{ .Values.msgTopologyOperator.metrics.service.type }}
  {{- if (or (eq .Values.msgTopologyOperator.metrics.service.type "LoadBalancer") (eq .Values.msgTopologyOperator.metrics.service.type "NodePort")) }}
  externalTrafficPolicy: {{ .Values.msgTopologyOperator.metrics.service.externalTrafficPolicy | quote }}
  {{- end }}
  {{ if .Values.msgTopologyOperator.metrics.service.clusterIP }}
  clusterIP: {{ .Values.msgTopologyOperator.metrics.service.clusterIP }}
  {{ end }}
  {{ if eq .Values.msgTopologyOperator.metrics.service.type "LoadBalancer" }}
  loadBalancerSourceRanges: {{ .Values.msgTopologyOperator.metrics.service.loadBalancerSourceRanges }}
  {{ end }}
  {{- if (and (eq .Values.msgTopologyOperator.metrics.service.type "LoadBalancer") (not (empty .Values.msgTopologyOperator.metrics.service.loadBalancerIP))) }}
  loadBalancerIP: {{ .Values.msgTopologyOperator.metrics.service.loadBalancerIP }}
  {{- end }}
  ports:
    - name: http
      port: {{ .Values.msgTopologyOperator.metrics.service.ports.http }}
      targetPort: http-metrics
      protocol: TCP
      {{- if (and (or (eq .Values.msgTopologyOperator.metrics.service.type "NodePort") (eq .Values.msgTopologyOperator.metrics.service.type "LoadBalancer")) (not (empty .Values.msgTopologyOperator.metrics.service.nodePorts.http))) }}
      nodePort: {{ .Values.msgTopologyOperator.metrics.service.nodePorts.http }}
      {{- else if eq .Values.msgTopologyOperator.metrics.service.type "ClusterIP" }}
      nodePort: null
      {{- end }}
    {{- if .Values.msgTopologyOperator.metrics.service.extraPorts }}
    {{- include "common.tplvalues.render" (dict "value" .Values.msgTopologyOperator.metrics.service.extraPorts "context" $) | nindent 4 }}
    {{- end }}
  selector: {{- include "common.labels.matchLabels" . | nindent 4 }}
    app.kubernetes.io/component: messaging-topology-operator
{{- end }}
