{{- if .Values.msgTopologyOperator.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: messaging-topology-operator
    app.kubernetes.io/part-of: rabbitmq
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  name: {{ template "rmqco.msgTopologyOperator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace | quote }}
  {{- if or .Values.commonAnnotations .Values.msgTopologyOperator.serviceAccount.annotations }}
  annotations:
    {{- if .Values.msgTopologyOperator.serviceAccount.annotations }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.msgTopologyOperator.serviceAccount.annotations "context" $ ) | nindent 4 }}
    {{- end }}
    {{- if .Values.commonAnnotations }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
    {{- end }}
  {{- end }}
automountServiceAccountToken: {{ .Values.msgTopologyOperator.serviceAccount.automountServiceAccountToken }}
{{- end }}
