#!/bin/bash
export DOCKER_IMAGE_VERSION=${LOGSTASH_DOCKER_IMAGE_VERSION}
export RABBITMQ_USER=${RABBIT_USERNAME}
export SRV_INSTANCES=${LOGSTASH_SRV_INSTANCES}
export SRV_CPUS=${LOGSTASH_SRV_CPUS}
export SRV_MEM=${LOGSTASH_SRV_MEM}
