#!/bin/bash
export DOCKER_IMAGE_VERSION=${BAILE_HAPROXY_DOCKER_IMAGE_VERSION}
export S3_BUCKET=${AWS_S3_BUCKET_DOMAIN}
export BAILE_LB_URL=${BAILE_LB_URL}
export BAILE_INTERNAL_LB_URL=${BAILE_INTERNAL_LB_URL}
export BAILE_ADDRESS="${BAILE_HOST}:9000"
export SQL_SERVER_ADDRESS="${SQL_SERVER_HOST}:8000"
export SRV_INSTANCES=${BAILE_HAPROXY_SRV_INSTANCES}
export SRV_CPUS=${BAILE_HAPROXY_SRV_CPUS}
export SRV_MEM=${BAILE_HAPROXY_SRV_MEM}
export VPC_DNS=${BAILE_HAPROXY_VPC_DNS}
export BAILE_API_PATH=${BAILE_API_PATH}
export SQL_SERVER_API_PATH=${SQL_SERVER_API_PATH}
export DNS_RESOLVER=${BAILE_HAPROXY_DNS_RESOLVER}