#!/bin/bash
export DOCKER_IMAGE_VERSION=${PEGASUS_DOCKER_IMAGE_VERSION}
export HTTP_AUTH_USER_NAME=${PEGASUS_HTTP_AUTH_USER_NAME}
export SRV_INSTANCES=${PEGASUS_SRV_INSTANCES}
export SRV_CPUS=${PEGASUS_SRV_CPUS}
export SRV_MEM=${PEGASUS_SRV_MEM}
export AWS_S3_REGION=${AWS_DEFAULT_REGION}
export PEGASUS_AWS_S3_ACCESS_KEY_ID=${APP_AWS_ACCESS_KEY_ID}
export PEGASUS_AWS_S3_SECRET_ACCESS_KEY=${APP_AWS_SECRET_ACCESS_KEY}
export AWS_REDSHIFT_URL="jdbc:redshift://${REDSHIFT_HOST}:5439/dev"
export AWS_REDSHIFT_USER=${REDSHIFT_USER}
export RABBIT_HOSTS=${RABBIT_HOSTS}
export RABBIT_USERNAME=${RABBIT_USERNAME}
