addSbtPlugin("com.frugalmechanic" % "fm-sbt-s3-resolver" % "0.14.0")
addSbtPlugin("org.scoverage" % "sbt-scoverage" % "1.5.1")
addSbtPlugin("com.codacy" % "sbt-codacy-coverage" % "1.3.12")
addSbtPlugin("com.typesafe.sbt" % "sbt-native-packager" % "1.3.4")
addSbtPlugin("com.typesafe.sbt" % "sbt-git" % "0.9.3")
addSbtPlugin("com.github.gseitz" % "sbt-release" % "1.0.9")
addSbtPlugin("com.github.tkawachi" % "sbt-repeat" % "0.1.0")
addSbtPlugin("com.geirsson" % "sbt-scalafmt" % "1.5.1")
