ARG IMAGE

FROM $IMAGE

ARG APP_NAME

WORKDIR /opt/docker

COPY files/aws-java-sdk-us-iso-east-1-overrides.jar lib/aws-java-sdk-us-iso-east-1-overrides.jar
COPY files/ca.der ca.der

RUN sed -i.bak 's/app_classpath="/&$lib_dir\/aws-java-sdk-us-iso-east-1-overrides.jar:/' /opt/docker/bin/$APP_NAME

USER root

RUN if echo "$JAVA_HOME" | grep jre; then keytool -noprompt -importcert -alias c2s -keystore $JAVA_HOME/lib/security/cacerts -storepass changeit -file ca.der; else keytool -noprompt -importcert -alias c2s -keystore $JAVA_HOME/jre/lib/security/cacerts -storepass changeit -file ca.der; fi
