---

# Only needed if we want to run docker containers on captain
# Needs to be fixed.
# - name: Login to dockerhub
#   docker_login:
#     registry: index.docker.io/v1/
#     email: "{{ email }}"
#     username: "{{ docker_login_username }}"
#     password: "{{ docker_registry_auth_token }}"

- name: Install percona-mongo
  yum:
    name: "{{ percona_mongo_download_url }}"
    state: present

- name: Install percona-mongo tools
  yum:
    name: "{{ percona_mongo_tools_download_url }}"
    state: present

- name: Download dcos cli
  get_url:
    url: "{{ dcos_cli_download_url }}"
    dest: /usr/local/bin/dcos
    mode: 0755

- name: Symlink /usr/local/bin/dcos to /usr/bin/dcos
  file:
    src: /usr/local/bin/dcos
    dest: /usr/bin/dcos
    state: link

- name: Copy services configuration files
  copy:
   dest: /opt/
   src: dcos_services
   owner: root
   group: root
   mode: 0644

- name: Copy tools files
  copy:
   dest: /opt/
   src: tools
   owner: root
   group: root
   mode: 0644

- name: Copy java installation file
  copy:
    dest: /opt/
    src: java
    owner: root
    group: root
    mode: 0644
  when: "private_deployment != 'true'"

- name: Install java
  command: sh /opt/java/install_java.sh
  when: "private_deployment != 'true'"

- name: Generate /etc/environment file
  template:
    src: etc/environment.j2
    dest: /etc/environment
    mode: 0644
