{{- if and .Values.clusterOperator.metrics.serviceMonitor.enabled .Values.clusterOperator.metrics.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ template "rmqco.clusterOperator.fullname" . }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: rabbitmq-operator
    app.kubernetes.io/part-of: rabbitmq
    {{- if .Values.clusterOperator.metrics.serviceMonitor.additionalLabels }}
    {{- include "common.tplvalues.render" (dict "value" .Values.clusterOperator.metrics.serviceMonitor.additionalLabels "context" $) | nindent 4 }}
    {{- end }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  namespace: {{ .Release.Namespace | quote }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  jobLabel: {{ .Values.clusterOperator.metrics.serviceMonitor.jobLabel }}
  selector:
    matchLabels: {{- include "common.labels.matchLabels" . | nindent 6 }}
      app.kubernetes.io/component: rabbitmq-operator
      {{- if .Values.clusterOperator.metrics.serviceMonitor.selector }}
      {{- include "common.tplvalues.render" ( dict "value" .Values.clusterOperator.metrics.serviceMonitor.selector "context" $ ) | nindent 6 }}
      {{- end }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  endpoints:
    - port: http
      {{- if .Values.clusterOperator.metrics.serviceMonitor.interval }}
      interval: {{ .Values.clusterOperator.metrics.serviceMonitor.interval }}
      {{- end }}
      {{- if .Values.clusterOperator.metrics.serviceMonitor.honorLabels }}
      honorLabels: {{ .Values.clusterOperator.metrics.serviceMonitor.honorLabels }}
      {{- end }}
      {{- if .Values.clusterOperator.metrics.serviceMonitor.scrapeTimeout }}
      scrapeTimeout: {{ .Values.clusterOperator.metrics.serviceMonitor.scrapeTimeout }}
      {{- end }}
      {{- if .Values.clusterOperator.metrics.serviceMonitor.metricRelabelings }}
      metricRelabelings: {{ toYaml .Values.clusterOperator.metrics.serviceMonitor.metricRelabelings | nindent 8 }}
      {{- end }}
      {{- if .Values.clusterOperator.metrics.serviceMonitor.relabelings }}
      relabelings: {{ toYaml .Values.clusterOperator.metrics.serviceMonitor.relabelings | nindent 8 }}
      {{- end }}
{{- end }}
