---

common_default_packages:
  - python-pip
  - jq
  - curl
  - tar
  - xz
  - zip
  - unzip
  - ipset
  - ntp
  - cloud-init

common_pip_packages:
  - awscli

common_removed_packages:
  - chrony

common_disk:
  xvde:
    filesystem:  ext4
    fs_opts:     -L mesos
    mount_point: /var/lib/mesos

  xvdf:
    filesystem:  ext4
    fs_opts:     -L docker
    mount_point: /var/lib/docker

  xvdg:
    filesystem:  ext4
    fs_opts:     -L dcos
    mount_point: /dcos/volume0

  xvdh:
    filesystem:  ext4
    fs_opts:     -L log
    mount_point: /var/log
