#!/bin/bash
export DOCKER_IMAGE_VERSION=${CORTEX_DOCKER_IMAGE_VERSION}
export HTTP_SEARCH_USER_NAME=${CORTEX_HTTP_SEARCH_USER_NAME}
export RABBIT_HOSTS=${RABBIT_HOSTS}
export RABBIT_USERNAME=${RABBIT_USERNAME}
export ARIES_REST_URL=${ARIES_REST_URL}
export ARIES_REST_VERSION=${CORTEX_ARIES_REST_VERSION}
export ARIES_SEARCH_USER_NAME=${ARIES_HTTP_SEARCH_USER_NAME}
export ARIES_COMMAND_USER_NAME=${ARIES_HTTP_COMMAND_USER_NAME}
export SRV_INSTANCES=${CORTEX_SRV_INSTANCES}
export SRV_CPUS=${CORTEX_SRV_CPUS}
export SRV_MEM=${CORTEX_SRV_MEM}
