#!/bin/bash
export DOCKER_IMAGE_VERSION=${ARIES_DOCKER_IMAGE_VERSION}
export HTTP_SEARCH_USER_NAME=${ARIES_HTTP_SEARCH_USER_NAME}
export HTTP_COMMAND_USER_NAME=${ARIES_HTTP_COMMAND_USER_NAME}
export ELASTIC_HOST=${ELASTIC_HOST}
export ELASTIC_PORT=${ELASTIC_PORT}
export ELASTIC_SSL=${ELASTIC_SSL}
export ELASTIC_JOB_INDEX=${ARIES_ELASTIC_JOB_INDEX}
export ELASTIC_HEARTBEAT_INDEX=${ARIES_ELASTIC_HEARTBEAT_INDEX}
export SRV_INSTANCES=${ARIES_SRV_INSTANCES}
export SRV_CPUS=${ARIES_SRV_CPUS}
export SRV_MEM=${ARIES_SRV_MEM}
